from django.urls import path
from . import views
app_name = "operations"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path(
        "tasks/",
        views.task_list,
        name="task_list",
    ),
    path(
        "tasks/new/",
        views.task_create,
        name="task_create",
    ),
    path(
        "tasks/<int:pk>/edit/",
        views.task_edit,
        name="task_edit",
    ),
    path(
        "tasks/<int:pk>/complete/",
        views.task_complete,
        name="task_complete",
    ),
    path(
        "issues/",
        views.issue_list,
        name="issue_list",
    ),
    path(
        "issues/new/",
        views.issue_create,
        name="issue_create",
    ),
    path(
        "issues/<int:pk>/edit/",
        views.issue_edit,
        name="issue_edit",
    ),
    path(
        "issues/<int:pk>/resolve/",
        views.issue_resolve,
        name="issue_resolve",
    ),
    path(
        "handover/",
        views.handover_list,
        name="handover_list",
    ),
    path(
        "handover/new/",
        views.handover_create,
        name="handover_create",
    ),
    path(
        "handover/<int:pk>/resolve/",
        views.handover_resolve,
        name="handover_resolve",
    ),
]