from django.urls import path
from . import views
app_name = "operations"
urlpatterns = [
    path(
        "",
        views.property_home,
        name="property_home",
    ),
    path(
        "p/<slug:property_slug>/",
        views.dashboard,
        name="dashboard",
    ),
    path(
        "p/<slug:property_slug>/tasks/",
        views.task_list,
        name="task_list",
    ),
    path(
        "p/<slug:property_slug>/tasks/new/",
        views.task_create,
        name="task_create",
    ),
    path(
        "p/<slug:property_slug>/tasks/<int:pk>/edit/",
        views.task_edit,
        name="task_edit",
    ),
    path(
        "p/<slug:property_slug>/tasks/<int:pk>/complete/",
        views.task_complete,
        name="task_complete",
    ),
    path(
        "p/<slug:property_slug>/issues/",
        views.issue_list,
        name="issue_list",
    ),
    path(
        "p/<slug:property_slug>/issues/new/",
        views.issue_create,
        name="issue_create",
    ),
    path(
        "p/<slug:property_slug>/issues/<int:pk>/edit/",
        views.issue_edit,
        name="issue_edit",
    ),
    path(
        "p/<slug:property_slug>/issues/<int:pk>/resolve/",
        views.issue_resolve,
        name="issue_resolve",
    ),
    path(
        "p/<slug:property_slug>/handover/",
        views.handover_list,
        name="handover_list",
    ),
    path(
        "p/<slug:property_slug>/handover/new/",
        views.handover_create,
        name="handover_create",
    ),
    path(
        "p/<slug:property_slug>/handover/<int:pk>/resolve/",
        views.handover_resolve,
        name="handover_resolve",
    ),
    path(
        "p/<slug:property_slug>/checklists/",
        views.checklist_list,
        name="checklist_list",
    ),
    path(
        "p/<slug:property_slug>/checklists/<int:pk>/start/",
        views.checklist_start,
        name="checklist_start",
    ),
    path(
        "p/<slug:property_slug>/checklists/run/<int:pk>/",
        views.checklist_run,
        name="checklist_run",
    ),
    path(
        "p/<slug:property_slug>/checklists/run/<int:run_pk>/item/<int:item_pk>/",
        views.checklist_item_toggle,
        name="checklist_item_toggle",
    ),
    path(
        "p/<slug:property_slug>/checklists/run/<int:pk>/complete/",
        views.checklist_complete,
        name="checklist_complete",
    ),
    path(
        "p/<slug:property_slug>/team/",
        views.team_list,
        name="team_list",
    ),
    path(
        "p/<slug:property_slug>/team/new/",
        views.team_member_create,
        name="team_member_create",
    ),
    path(
        "p/<slug:property_slug>/team/<int:pk>/edit/",
        views.team_member_edit,
        name="team_member_edit",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/",
        views.checklist_manage,
        name="checklist_manage",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/new/",
        views.checklist_create,
        name="checklist_create",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/<int:pk>/",
        views.checklist_edit,
        name="checklist_edit",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/<int:checklist_pk>/items/new/",
        views.checklist_item_create,
        name="checklist_item_create",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/<int:checklist_pk>/items/<int:item_pk>/edit/",
        views.checklist_item_edit,
        name="checklist_item_edit",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/<int:checklist_pk>/items/<int:item_pk>/delete/",
        views.checklist_item_delete,
        name="checklist_item_delete",
    ),
    path(
        "p/<slug:property_slug>/checklists/manage/"
        "<int:checklist_pk>/items/reorder/",
        views.checklist_item_reorder,
        name="checklist_item_reorder",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/",
        views.recurring_task_list,
        name="recurring_task_list",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/new/",
        views.recurring_task_create,
        name="recurring_task_create",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/generate/",
        views.recurring_task_generate_today,
        name="recurring_task_generate_today",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/<int:pk>/edit/",
        views.recurring_task_edit,
        name="recurring_task_edit",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/<int:pk>/toggle/",
        views.recurring_task_toggle,
        name="recurring_task_toggle",
    ),
    path(
        "p/<slug:property_slug>/tasks/recurring/<int:pk>/delete/",
        views.recurring_task_delete,
        name="recurring_task_delete",
    ),
    path(
        "p/<slug:property_slug>/activity/",
        views.activity_list,
        name="activity_list",
    ),
    path(
        "p/<slug:property_slug>/tasks/<int:task_pk>/assign/",
        views.task_quick_assign,
        name="task_quick_assign",
    ),
    path(
        "p/<slug:property_slug>/issues/<int:issue_pk>/assign/",
        views.issue_quick_assign,
        name="issue_quick_assign",
    ),
    path(
        "p/<slug:property_slug>/notifications/",
        views.notification_list,
        name="notification_list",
    ),
    path(
        "p/<slug:property_slug>/notifications/<int:notification_pk>/read/",
        views.notification_mark_read,
        name="notification_mark_read",
    ),
    path(
        "p/<slug:property_slug>/notifications/read-all/",
        views.notification_mark_all_read,
        name="notification_mark_all_read",
    ),
    path(
        "p/<slug:property_slug>/notifications/<int:notification_pk>/open/",
        views.notification_open,
        name="notification_open",
    ),
]