# Generated by Django 6.1 on 2026-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisationinvitation'),
        ('properties', '0003_alter_property_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationinvitation',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='organisation_invitations', to='properties.property'),
        ),
        migrations.AddField(
            model_name='organisationinvitation',
            name='property_role',
            field=models.CharField(choices=[('owner', 'Owner / Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('team_member', 'Team Member')], default='team_member', max_length=20),
        ),
    ]
