# Generated by Django 6.1 on 2026-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organisationinvitation_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
