# Generated by Django 6.1 on 2026-08-31 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('founder_beta', 'Founder Beta'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], default='founder_beta', max_length=30)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('property_limit', models.PositiveIntegerField(default=1)),
                ('member_limit', models.PositiveIntegerField(default=10)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='properties.organisation')),
            ],
        ),
    ]
