# Generated by Django 6.1 on 2026-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_organisationsubscriptionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscriptionevent',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('plan_change', 'Plan Change')], default='status_change', max_length=30),
        ),
        migrations.AddField(
            model_name='organisationsubscriptionevent',
            name='new_plan',
            field=models.CharField(blank=True, choices=[('founder_beta', 'Founder Beta'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organisationsubscriptionevent',
            name='previous_plan',
            field=models.CharField(blank=True, choices=[('founder_beta', 'Founder Beta'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organisationsubscriptionevent',
            name='new_status',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organisationsubscriptionevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=20, null=True),
        ),
    ]
