# Generated by Django 6.1 on 2026-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_organisationsubscriptionevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='billing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='billing_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
