# Generated by Django 6.1 on 2026-08-31 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_organisationsubscription_billing_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationBillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('invoice_created', 'Invoice Created'), ('invoice_paid', 'Invoice Paid'), ('refund_issued', 'Refund Issued'), ('checkout_created', 'Checkout Created'), ('provider_event', 'Provider Event')], max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='manual', max_length=20)),
                ('provider_event_id', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='properties.organisation')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='properties.organisationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
