# Generated by Django 6.1 on 2026-08-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_organisationbillingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationBillingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(choices=[('founder_beta', 'Founder Beta'), ('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='manual', max_length=20)),
                ('provider_session_id', models.CharField(blank=True, max_length=255)),
                ('provider_checkout_url', models.URLField(blank=True, max_length=1000)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_sessions', to='properties.organisation')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_sessions', to='properties.organisationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
