# Generated by Django 6.1 on 2026-09-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_organisationbillingsession'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organisationbillingevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider', 'provider_event_id'), name='unique_billing_provider_event'),
        ),
    ]
