# Generated by Django 6.1 on 2026-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_organisationbillingevent_unique_billing_provider_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending setup'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisationsubscriptionevent',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending setup'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organisationsubscriptionevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending setup'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=20, null=True),
        ),
    ]
