# Generated by Django 6.1 on 2026-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_organisationsubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationbillingsession',
            name='provider_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
