"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(
    BASE_DIR / ".env"
)
def env_bool(name, default=False):
    value = os.getenv(
        name,
        str(default),
    )
    return value.lower() in {
        "1",
        "true",
        "yes",
        "on",
    }
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only",
)
DEBUG = env_bool(
    "DEBUG",
    True,
)
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        (
            "127.0.0.1,"
            "localhost,"
            ".ngrok-free.dev"
        ),
    ).split(",")
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "properties",
    "operations",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "accounts.context_processors.rk_ops_permissions",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "",
)
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": (
                "django.db.backends.sqlite3"
            ),
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
AUTHENTICATION_BACKENDS = [
    "accounts.backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
if DEBUG:
    MAILERS = {
        "default": {
            "BACKEND": (
                "django.core.mail.backends.console.EmailBackend"
            ),
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": (
                "django.core.mail.backends.smtp.EmailBackend"
            ),
            "HOST": os.getenv(
                "EMAIL_HOST",
                "",
            ),
            "PORT": int(
                os.getenv(
                    "EMAIL_PORT",
                    "587",
                )
            ),
            "USERNAME": os.getenv(
                "EMAIL_HOST_USER",
                "",
            ),
            "PASSWORD": os.getenv(
                "EMAIL_HOST_PASSWORD",
                "",
            ),
            "USE_TLS": env_bool(
                "EMAIL_USE_TLS",
                True,
            ),
            "TIMEOUT": int(
                os.getenv(
                    "EMAIL_TIMEOUT",
                    "10",
                )
            ),
        },
    }
DEFAULT_FROM_EMAIL = (
    "RK Ops <hello@rkhospitality.studio>"
)
PAYPAL_MODE = os.getenv(
    "PAYPAL_MODE",
    "sandbox",
)
PAYPAL_CLIENT_ID = os.getenv(
    "PAYPAL_CLIENT_ID",
    "",
)
PAYPAL_CLIENT_SECRET = os.getenv(
    "PAYPAL_CLIENT_SECRET",
    "",
)
if PAYPAL_MODE == "live":
    PAYPAL_API_BASE_URL = (
        "https://api-m.paypal.com"
    )
else:
    PAYPAL_API_BASE_URL = (
        "https://api-m.sandbox.paypal.com"
    )
PAYPAL_PRODUCT_ID = os.getenv(
    "PAYPAL_PRODUCT_ID",
    "",
)
PAYPAL_STARTER_PLAN_ID = os.getenv(
    "PAYPAL_STARTER_PLAN_ID",
    "",
)
PAYPAL_GROWTH_PLAN_ID = os.getenv(
    "PAYPAL_GROWTH_PLAN_ID",
    "",
)
PAYPAL_PRO_PLAN_ID = os.getenv(
    "PAYPAL_PRO_PLAN_ID",
    "",
)
PAYPAL_WEBHOOK_ID = os.getenv(
    "PAYPAL_WEBHOOK_ID",
    "",
)
PAYPAL_STARTER_TRIAL_PLAN_ID = os.getenv(
    "PAYPAL_STARTER_TRIAL_PLAN_ID",
    "",
)
PAYPAL_GROWTH_TRIAL_PLAN_ID = os.getenv(
    "PAYPAL_GROWTH_TRIAL_PLAN_ID",
    "",
)
PAYPAL_PRO_TRIAL_PLAN_ID = os.getenv(
    "PAYPAL_PRO_TRIAL_PLAN_ID",
    "",
)
APP_BASE_URL = os.getenv(
    "APP_BASE_URL",
    "http://127.0.0.1:8000",
)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )
    # Start conservatively.
    # Increase once Railway + custom domain HTTPS
    # has been verified in production.
    SECURE_HSTS_SECONDS = int(
        os.getenv(
            "SECURE_HSTS_SECONDS",
            "0",
        )
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        env_bool(
            "SECURE_HSTS_INCLUDE_SUBDOMAINS",
            False,
        )
    )
    SECURE_HSTS_PRELOAD = (
        env_bool(
            "SECURE_HSTS_PRELOAD",
            False,
        )
    )