# Generated by Django 6.1 on 2026-08-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_recurringtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
