# Generated by Django 6.1 on 2026-08-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_recurringtask_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='operations.recurringtask'),
        ),
    ]
