# Generated by Django 6.1 on 2026-08-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_recurringtask_recurring_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
