# Generated by Django 6.1 on 2026-08-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_recurringtask_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtask',
            name='recurring_source',
        ),
        migrations.RemoveField(
            model_name='recurringtask',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='operations.recurringtask'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
