# Generated by Django 6.1 on 2026-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_recurringtask_recurring_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='last_generated_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
