# Generated by Django 6.1 on 2026-08-29 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_recurringtask_last_generated_at_and_more'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('task_created', 'Task created'), ('task_completed', 'Task completed'), ('issue_reported', 'Issue reported'), ('issue_resolved', 'Issue resolved'), ('checklist_started', 'Checklist started'), ('checklist_completed', 'Checklist completed'), ('handover_added', 'Handover note added'), ('team_member_added', 'Team member added'), ('recurring_generated', 'Recurring task generated')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
