# Generated by Django 6.1 on 2026-08-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'None'), ('watch', 'Watch'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_completed', 'Task completed'), ('task_assigned', 'Task assigned'), ('issue_reported', 'Issue reported'), ('issue_resolved', 'Issue resolved'), ('issue_assigned', 'Issue assigned'), ('checklist_started', 'Checklist started'), ('checklist_completed', 'Checklist completed'), ('handover_added', 'Handover note added'), ('team_member_added', 'Team member added'), ('recurring_generated', 'Recurring task generated')], max_length=40),
        ),
    ]
