# Generated by Django 6.1 on 2026-08-30 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_task_escalation_level_alter_activitylog_event_type'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_completed', 'Task completed'), ('task_assigned', 'Task assigned'), ('issue_reported', 'Issue reported'), ('issue_resolved', 'Issue resolved'), ('issue_assigned', 'Issue assigned'), ('checklist_started', 'Checklist started'), ('checklist_completed', 'Checklist completed'), ('handover_added', 'Handover note added'), ('team_member_added', 'Team member added'), ('recurring_generated', 'Recurring task generated'), ('task_escalated', 'Task escalated'), ('task_deescalated', 'Task de-escalated')], max_length=40),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='properties.property')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
