# Generated by Django 6.1 on 2026-09-04 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_notification_issue_notification_task'),
        ('properties', '0011_alter_organisationsubscription_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_source__isnull', False)), fields=('recurring_source', 'scheduled_date'), name='unique_recurring_task_per_date'),
        ),
    ]
